[build]
builder = "DOCKERFILE"
dockerfilePath = "mcp_server/Dockerfile"

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
port = 8000
timeout = 100
interval = 30
